"""empty message

Revision ID: e8cc751bcf8e
Revises: 87f78fbb58ba
Create Date: 2018-07-15 12:18:35.755387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cc751bcf8e'
down_revision = '87f78fbb58ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShippingInfo', sa.Column('city', sa.String(), nullable=False))
    op.add_column('ShippingInfo', sa.Column('country', sa.String(), nullable=False))
    op.add_column('ShippingInfo', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('ShippingInfo', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ShippingInfo', 'state')
    op.drop_column('ShippingInfo', 'postal_code')
    op.drop_column('ShippingInfo', 'country')
    op.drop_column('ShippingInfo', 'city')
    # ### end Alembic commands ###
